# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.




#  TODO: had to hardcode item menu with # because of the /global2020/, everything is fucked.
[[main]]
  pre = "<i class='fas fa-brain'></i>"
  name = " Home"
  url = "/"
  weight = 10

[[main]]
  name = "Events"
  url = "/events"
  weight = 20
  # identifier = "event"

# [[main]]
#   name = "View 2020 Events"
#   url = "/events#talk_list"
#   weight = 20
#   parent = "event"

# [[main]]
#   name = "Host an Event"
#   url = "/events#host-a-local-brainhack"
#   weight = 21
#   parent = "event"

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 30

[[main]]
  name = "FAQ"
  url = "/faq"
  weight = 40
  # identifier = "faq"

# [[main]]
#   name = "General FAQ"
#   url = "/faq#general-questions"
#   weight = 41
#   parent = "faq"
# [[main]]
#   name = "FAQ for attendees"
#   url = "https://brainhack.org/faq/#attendees"
#   weight = 42
#   parent = "faq"

# [[main]]
#   name = "FAQ for hosts"
#   url = "/faq/#hosts"
#   weight = 43
#   parent = "faq"

[[main]]
  name = "Contact"
  url = "/#contact"
  weight = 60

[[main]]
  name = "Code of Conduct"
  url = "/code-of-conduct"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
