# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  pre = "<i class='fas fa-brain'></i>"
  name = " Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "Events"
  url = "#events"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "FAQ"
  # url = "/faq"
  weight = 40
  identifier = "faq"

[[main]]
  name = "General FAQ"
  url = "/faq#general-questions"
  weight = 41
  parent = "faq"
[[main]]
  name = "FAQ for attendees"
  url = "/faq#attendees"
  weight = 42
  parent = "faq"

[[main]]
  name = "FAQ for hosts"
  url = "/faq#hosts"
  weight = 43
  parent = "faq"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "Code of Conduct"
  url = "/code-of-conduct"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
