blank_issues_enabled: false
contact_links:
  - name: BIDS NeuroStars forum
    url: https://neurostars.org/
    about: Ask (and answer) concrete technical questions or about implementation details around BIDS.
