name: Project submission template

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to submit a project

title: "[Project]: "

labels: ["project"]

# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines
        We are very excited to meet you at Brainhack Global 2021 🎉. To submit a project, you need to be an attendee to one of the Brainhack Global 2021 events listed on the [Brainhack Global 2021 webpage](https://brainhack.org/global2021/events/). Please, register for the event that is most suitable to your location, time zone, interest, and/or project prior to submitting one. Thank you!

        We have prepared a checklist to help with your project submission. Here is how to proceed:

        Before filling in any part please check items in the checklist below as you go through them.

        Once you are done (at least all 'required' items must be provided), please delete the "Guidelines" section, submit your issue and add a comment saying 'Hi @Brainhack-Global/project-monitors: my project is ready!'

        Thank you!

        After the issue is submitted, we will assign a 'project monitor' from the event location that you are registered with to review your submission. Once the submission is approved by the 'project monitor', they will add the label 'Project is ready' and it will appear on [Brainhack Global 2021 Projects](https://brainhack.org/global2021/projects) page with a separate project dedicated webpage.

        Note that you can always update your issue which will also change your page on the website accordingly.

        If at any time you need help from us or anything is unclear, please add a comment and ping your project monitor. Our team is here to help! -->

  - type: markdown
    attributes:
      value: |
        ## Project info

  - type: textarea
    attributes:
      label: Title
      description:
        Add a title that reflects what the code (or content) will do in a way
        that makes sense to newcomers who want to contribute to your project.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Project lead
      description:
        Add full name (and Twitter / Mattermost handle if possible) of the
        contact person.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Project collaborators
      description:
        Add full names (and Twitter / Mattermost handle if possible) of any
        person contributing to the project. Try to follow the [all-contributors
        specification](https://github.com/all-contributors/all-contributors).
        Contributions of any kind are welcome!
    validations:
      required: true

  - type: dropdown
    id: event
    attributes:
      description:
        Specify the city and country of the Brainhack Global 2021 event that you
        registered for. If your local event has a special name or topic, please
        do specify that as well to help us distinguish between potential events
        in the same city.
      label: Registered Brainhack Global 2021 Event
      multiple: true
      options:
        - nordic
        - donostia
    validations:
      required: true

  - type: textarea
    attributes:
      label: Project Description
      description: Add a brief description of the project. Try to include all
        the relevant information to answer the following questions

        What are you doing, for who, and why;

        What makes your project special and exciting;

        A short example;

        How to get started;

        Where to find key resources
    validations:
      required: true

  # - type: checkboxes
  #   attributes:
  #     label: Is there an existing issue for this?
  #     description:
  #       Please search to see if an issue already exists for the bug you
  #       encountered.
  #     options:
  #       - label: I have searched the existing issues
  #       - label: tests

  # **Data to use:**
  # <!-- If your project uses data, add a short description of the data and a link to its source. -->

  # **Link to project repository/sources:**
  # <!-- Add a link to the project’s GitHub repo or website. -->

  # **Goals for Brainhack Global 2021:**
  # <!-- Add a list of milestones or deliverables that you expect to achieve during the event. Try to provide goals of varying complexity for contributors with different sets of skills. -->

  # **Good first issues:**
  # <!-- Add a list of tasks to help new contributors find easy gateways into open source projects. -->

  # 1.
  # 2.

  # **Skills:**
  # <!-- Add a list of skills needed to contribute to this project. Try to think of both coding and non-coding skills. You can provide predefined skill levels, but it’s better if you give concrete examples of the type of task contributors will be facing. Please make sure you create equal opportunities to accommodate the newcomers in your project to learn from each other and share the experiences. -->

  # **Tools/Software/Methods to Use:**
  # <!-- Add a list of tools/software/methods that are advised to be installed/reviewed ahead of the event to gain a bit of time with the installation of the software, preparation of the environments or describing the methods that will be needed to contribute to this project. Try to think of both coding and non-coding details regarding such to be listed. -->

  # **Communication channels:**
  # <!-- Add links to chat channels in Slack or Mattermost -->

  # <!-- [ ] Video channel: Please write here the communication channel (Zoom, Jitsi, Twitch, or any other platform) you will be using to work collaboratively however please keep them as commented to avoid any public sharing. Once you set up your project Mattermost communication channel, make sure you write the link of the video channel at the header of the Mattermost channel for your attendees to know -->

  #
  # LABELS
  #

  - type: markdown
    attributes:
      value: |
        ## Project labels

  - type: dropdown
    id: type
    attributes:
      label: Type
      multiple: true
      options:
        - coding_methods
        - data_management
        - documentation
        - method_development
        - pipeline_development
        - tutorial_recording
        - visualization
        - other
    validations:
      required: true

  - type: dropdown
    id: development_status
    attributes:
      label: Development status
      multiple: false
      options:
        - 0_concept_no_content
        - 1_basic structure
        - 2_releases_existing
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      multiple: true
      options:
        - bayesian_approaches
        - causality
        - connectome
        - data_visualisation
        - deep_learning
        - diffusion
        - diversity_inclusivity_equality
        - EEG_EventRelatedResponseModelling
        - EEG_source_modelling
        - Granger_causality
        - hypothesis_testing
        - ICA
        - information_theory
        - machine_learning
        - MR_methodologies
        - neural_decoding
        - neural_encoding
        - neural_networks
        - PCA
        - physiology
        - reinforcement_learning
        - reproducible_scientific_methods
        - single_neuron_models
        - statistical_modelling
        - systems_neuroscience
        - tractography
        - other
    validations:
      required: true

  - type: dropdown
    id: tools
    attributes:
      label: Tools used
      multiple: true
      options:
        - AFNI
        - ANTs
        - BIDS
        - Brainstorm
        - CPAC
        - Datalad
        - DIPY
        - FieldTrip
        - fMRIPrep
        - Freesurfer
        - FSL
        - Jupyter
        - MNE
        - MRtrix
        - Nipype
        - NWB
        - SPM
        - other
        - not_applicable
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Programming language used
      multiple: true
      options:
        - C++
        - containerization
        - documentation
        - Java
        - Julia
        - Matlab
        - Python
        - R
        - shell_scripting
        - unix_command_line
        - html_css
        - other
        - not_applicable
    validations:
      required: true

  - type: dropdown
    id: modalities
    attributes:
      label: Modalities involved in the project
      multiple: true
      options:
        - behavioral
        - DWI
        - ECG
        - ECOG
        - EEG
        - eye_tracking
        - fMRI
        - fNIRS
        - MEG
        - MRI
        - PET
        - TDCS
        - TMS
        - other
        - not_applicable
    validations:
      required: true

  - type: dropdown
    id: git_level
    attributes:
      label: Git skills required to enter the project
      multiple: true
      options:
        - 0_no_git_skills
        - 1_commit_push
        - 2_branches_PRs
        - 3_continuous_integration
        - 4_not_applicable
    validations:
      required: true
# ## Project Submission

# ### Submission checklist

# *Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

# - [ ] Link to your project: could be a code repository, a shared document, etc.
# - [ ] Goals for Brainhack Global 2021: describe what you want to achieve during this brainhack.
# - [ ] Flesh out at least 2 “good first issues”: those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document.
# - [ ] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill. Use the issue labels for this purpose.
# - [ ] Chat channel: A link to a chat channel that will be used during the Brainhack Global 2021 event. This can be an existing channel or a new one. We recommend using the [Brainhack space on Mattermost](https://mattermost.brainhack.org/).
# <!-- [ ] Video channel: A link to a video channel that will be used during the Brainhack Global 2021 Brainhack. This can be an existing channel or a new one. For instance a [Jitsi meet room](https://meet.jit.si/). **Please, do not make the video channel public in here**: post a message in your chat channel and pin it so that it remains private, you do not get undesired content, and contributors can still have access to it..-->

# Optionally, you can also include information about:

# - [ ] Number of participants required.
# - [ ] Twitter-sized summary of your project pitch.
# - [ ] Provide an image of your project for the Brainhack Global 2021 website.
# <!-- You can put an image anywhere in this issue and it will be used to build your project page on the website. -->

# We would like to think about how you will credit and onboard new members to your project. If you’d like to share your thoughts with future project participants, you can include information about:

# - [ ] Specify how you will acknowledge contributions (e.g. listing members on a contributing page).
# - [ ] Provide links to onboarding documents if you have some:
