name: Generate project pages from project issues

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: python -m pip install --upgrade pip requests regex

    - name: Run script to generate separate pages from issues
      run: |
        python issues_to_pages.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: publish-project
        commit-message: Convert issues to project pages, yay!
        assignees: SamGuay, complexbrains
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
